FROM alpine:3.24 AS builder

ARG HUGO_VERSION=0.163.1
ARG PANDOC_VERSION=3.10

RUN apk add --no-cache wget git nodejs npm chromium font-noto-emoji zip unzip \
    && wget -O hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_linux-amd64.tar.gz \
    && tar -xzf hugo.tar.gz -C /usr/local/bin \
    && rm hugo.tar.gz \
    && wget -O pandoc.tar.gz https://github.com/jgm/pandoc/releases/download/${PANDOC_VERSION}/pandoc-${PANDOC_VERSION}-linux-amd64.tar.gz \
    && tar -xzf pandoc.tar.gz --strip-components=2 -C /usr/local/bin pandoc-${PANDOC_VERSION}/bin/pandoc \
    && rm pandoc.tar.gz

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run render-mermaid

ARG BASE_URL
RUN if [ -n "$BASE_URL" ]; then \
      hugo --minify --baseURL "$BASE_URL"; \
    else \
      hugo --minify; \
    fi

RUN npm run render-downloads


FROM nginxinc/nginx-unprivileged:stable-alpine-slim

COPY --from=builder /app/public /usr/share/nginx/html
COPY container/nginx.conf /etc/nginx/nginx.conf
COPY container/default.conf /etc/nginx/conf.d/default.conf
COPY container/security-headers.conf /etc/nginx/security-headers.conf

EXPOSE 8080
