FROM alpine:3.21 AS builder

ARG HUGO_VERSION=0.154.4

RUN apk add --no-cache wget git nodejs npm chromium \
    && wget -O hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_linux-amd64.tar.gz \
    && tar -xzf hugo.tar.gz -C /usr/local/bin \
    && rm hugo.tar.gz

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run render-mermaid

ARG BASE_URL
RUN if [ -n "$BASE_URL" ]; then \
      hugo --minify --baseURL "$BASE_URL"; \
    else \
      hugo --minify; \
    fi


FROM nginxinc/nginx-unprivileged:stable-alpine-slim

COPY --from=builder /app/public /usr/share/nginx/html
COPY container/nginx.conf /etc/nginx/nginx.conf
COPY container/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080
